### ISSUE TITLE
add people and orgs object to  the request object

### ISSUE THREAD

**Issue by jay-meister** [postgres-plugin/people#11]
Along similar lines to [this](https://github.com/postgres-plugin/challenges/issues/33) in challenges, we want all functions to be attached to `request.pg.___.`.

I think it would make naming a lot clearer if we can expose 2 objects, people and orgs, as they will both hold similar functions but for different data types.

If we expose both `.orgs` and `.people` we could follow the following naming:
- `request.pg.people.add()` & `request.pg.orgs.add()`
- `request.pg.people.update()` & `request.pg.orgs.update()`

As opposed to:
- `request.pg.people.addOrg()` Add organisation is not linked to people.
...

**Comment by SimonLab** [comment]
resolved with #18
