### ISSUE TITLE
How to attached methods to an app?

### ISSUE THREAD

**Issue by SimonLab** [postgres-plugin/people#17]
At the moment we are adding the postgres functions to the request object by using the [server.ext api](https://github.com/postgres-plugin/people/blob/d34c1b2ff0ce85d8898123daff52d2c16452c9fe/lib/index.js#L18). This means that at each requests we are assigning the pg functions to the request object.
So instead of using the [extension api](http://hapijs.com/api#serverextevents) can we use the [decorate](http://hapijs.com/api) one and does this only add the function once to the request?

**Comment by SimonLab** [comment]
The decorate api seems more to be useful when we want to add specific functions on the requests object, so the decorate function will be executed again for each requests. The structure we use to attached functions (request.pg.tableName) make it difficult to implement with the method object (we need first to decorate the request object with the object pg.tableName then we will be able to attach some functions) but I still would like to keep the structure as it make it clear which functions is called in the handlers. A good solution is to attached the postgres function to the server object instead of the request object with the [method api](http://hapijs.com/api#servermethodname-method-options), the functions will only be attached once when we register the plugin and we can keep our structure: the method api "supports using nested names such as utils.users.get" :+1: "Server methods are functions registered with the server and used throughout the application as a common utility"

Finally we can access server methods from the request object so our handlers will only need a quick and small change to use our postgres queries:

```
function (request, reply) {
 // get the postgres method
 var pgFct = request.server.methods.pgFct;
 // then just call like the function
 pgFct()
 ...
}
```

To conclude Hapi offer various ways to expose and add some functionalities to the request, reply and server objects:

- just add a value to the server - use [server.app](http://hapijs.com/api#serverapp)
- add specific functions at a certain point of the request cycle - use [server.ext](http://hapijs.com/api#serverextevents), this functions added with server.ext will be executed for each requests to the server!
- add some functionalities to the request - use [server.decorate](http://hapijs.com/api#serverdecoratetype-property-method-options), the functions will be executed for each requests!
- expose values from a plugin - use [server.expose](http://hapijs.com/api#serverexposekey-value) - the value will then be accessible from server.plugins.namOfThePlugins.value
- add method to the server - use [server.method](http://hapijs.com/api#servermethodname-method-options) ""

Add a comment if you know another way to expose/attached functionalities to an Hapi application :+1:

**Comment by jay-meister** [comment]
Sorry if i missed something, is there a problem with server.app? It seems like a very simple option.

**Comment by jay-meister** [comment]
@SimonLab is it ok to @jmurphyweb me in a new issue, as i don't get notifications if you don't.

**Comment by SimonLab** [comment]
Have a look at this [response](http://stackoverflow.com/questions/29562438/hapi-server-methods-vs-server-app-dosomething). At the moment I see server.app like a container for specific values or constants, and server.method  a way to add functions which can be shared at "server level".
@JMurphyWeb you need to watch the repo to see notification, not all the issues will be linked to you so I don't want to add your name on all of them (I can if you want to resolve all the issues :wink: )

**Comment by jay-meister** [comment]
OK, I am watching 👀

**Comment by jay-meister** [comment]
Merged
