### ISSUE TITLE
getById function

### ISSUE THREAD

**Issue by jay-meister** [postgres-plugin/people#19]
people.getById is needed for auth.js

Requested here:
https://github.com/emfoundation/ce100-app/issues/390

possible interface:
```js
request.pg.people.getById(id, function (err, person) {
```

This function should only ever return 1 or 0 people, I am thinking it could always return an array as it would be very easy to tell if there is a person using `person.length === 0`.

Thoughts @SimonLab ?

**Comment by SimonLab** [comment]
@JMurphyWeb sounds good, just a small modification on the interface, if we are happy to attached the functions to the server object it will be ```request.server.methods.pg.people.getById(id, function (err, person) {```

**Comment by jay-meister** [comment]
Looking at it, this will be exactly the same as 
```js
getByEmail()
```

We can instead expose a getBy function:
```js
getBy('email', emailAddress, cb)
getBy('id', userId, cb)
```
