### ISSUE TITLE
edit getActiveOrgs so that it can take in a filter parameter

### ISSUE THREAD

**Issue by mk4111** [postgres-plugin/people#29]
We need to be able to query the pg-database for active orgs, which have a certain tag associated with it.

Currently addActiveOrgs.js returns just a string. We need to make this a function, which takes in a filter parameter, and construct a query which will be able to return organisations associated with a certain tag.

Will need to deal with lookup table (tags_organisations) first, and do a 'join' based on this.

**Comment by mk4111** [comment]
renaming function to `orgsGetByTag` and removed mission_statement from response object, as it is not needed in the general view

**Comment by SimonLab** [comment]
This issue looks very similar to #26. Is it a duplicate or is the logic of the functions different?
