### ISSUE TITLE
Formatter crashes if no data is returned from getByTag

### ISSUE THREAD

**Issue by mk4111** [postgres-plugin/people#33]
Need to fix instances where getByTag query returns an empty array, and catch for when data[0] does not exist.

>> Could just check for the empty array and then make another request to just get tagName? But this would be a much less elegant solutio

**Comment by mk4111** [comment]
Trying to fix this. Will spend an hour doing so.

Current issue is that the postgres query returns an empty array, as opposed to 
```js
[
  {
    tag_name: Corporate 
  }
]
```

Need to change query so that we can return this at the very least

**Comment by mk4111** [comment]
Update to current situation:

There are 4 situations to cover. The one being looked at currently is the query which _should_ return:
- active organisations only (for primary)
- organisations associated to a tag (filtered)

The query causing issues (i.e. query which returns _empty_) is:
```js
SELECT 
tags.name AS filter_tag, 
organisations.id AS id, 
... // other fields to return
organisations.active AS active 
FROM 
organisations JOIN tags_organisations 
ON (tags_organisations.organisations_id = organisations.id)
JOIN tags
ON (tags_organisations.tags_id = tags.id)
 WHERE tags.id = 2 // example of a tagId
 AND organisations.active = true
 ORDER BY organisations.name ASC;
```
I've had a play with this, and found the below:
```js
SELECT 
tags.name AS filter_tag, 
organisations.id AS id, 
... // other fields to return
organisations.active AS active 
FROM 
organisations JOIN tags_organisations 
ON (tags_organisations.organisations_id = organisations.id)
RIGHT OUTER JOIN tags 
ON (tags_organisations.tags_id = tags.id WHERE tags.id = 2); //2 is an example tag
```
The above works, and yields the following:

![screenshot from 2016-12-02 12-02-02](https://cloud.githubusercontent.com/assets/13470325/20834518/c2ddcf98-b88d-11e6-9db7-5d00faab7148.png)

Unfortunately, an empty array is returned as soon as we append the following to the WHERE tagId = 2 constraint
```
AND organisations.active = true
```

**Comment by jay-meister** [comment]
This worked for me:
```sql
SELECT
*
FROM
organisations JOIN tags_organisations
ON (tags_organisations.organisations_id = organisations.id)
RIGHT OUTER JOIN tags
ON (tags_organisations.tags_id = tags.id)
WHERE tags.id = 
AND organisations.active IS NOT FALSE;
```

**Comment by jay-meister** [comment]
@mk4111It might not be necessary, but I worry it will return no results if the org has no tags attached. I think we should add more tests for these sorts of circumstances.

```sql
SELECT
*
FROM
organisations 
LEFT OUTER JOIN tags_organisations
ON (tags_organisations.organisations_id = organisations.id)
```

**Comment by mk4111** [comment]
@JMurphyWeb - I agree, a bunch of tests to come!

I'll check out the IS NOT FALSE and let you know how it is! Pretty cool!

**Comment by mk4111** [comment]
:heart: :heart: :heart: it works!!
