### ISSUE TITLE
update query not working in application

### ISSUE THREAD

**Issue by jay-meister** [postgres-plugin/people#36]
In branch update-org, I have written an update query that spits out the following queries in my [endpoint test](https://github.com/postgres-plugin/people/pull/34/files#diff-6ffb553bbd46ebbb9f75e55b4d31ff1bR21):

`UPDATE organisations SET name = 'Google', logo_url = 'www.google.co', mission_statement = 'Change the internet' WHERE id = 1 ;`

`UPDATE organisations SET name = 'Google', logo_url = 'www.google.co', mission_statement = 'Change the internet' WHERE id = 100 ;`

The first is supposed to update, the second is supposed to error/return some response indicating it could not `UPDATE` an org that doesn't exist.

When I copy the queries into the psql terminal, I get `UPDATE 1` from the first, and `UPDATE 0` from the second. However when I run the tests, it seems like neither query updates the db and they both return an empty array.

I have not been able to locate any good documentation online so am struggling to debug.

**Comment by mk4111** [comment]
@JMurphyWeb - is this issue close-able now?

**Comment by jay-meister** [comment]
it is. thanks for pointing out.
